### ISSUE TITLE
Solid background behind the switcher

### ISSUE THREAD

**Issue by visualglitch91** [isaksamsten/niriswitcher#17]
I have this solid background behind the switcher, is this a known issue? I tried tweaking the css but I think it's something else.

![Image](https://github.com/user-attachments/assets/bc97e348-1e66-4faf-9610-be1cc61d267a)

**Comment by visualglitch91** [comment]
Oh yeah, I have catppuccin mocha, something there is forcing this solid bg... Thanks!

**Comment by isaksamsten** [comment]
Could you try with:

```css
window.background {
    background-color: transparent;
}
```

And see if that resolves it with catppuccin?
